version: '3.1'

services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: example
            POSTGRES_DATABASE: logs
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432



      